INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Indeed', 'Actually American miss no key law important.', 526.63, 567);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Great', 'Wall pick special few.', 197.59, 650);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'House', 'With young physical or.', 849.25, 517);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Continue', 'As keep popular take together.', 132.52, 668);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'School', 'Soon foot stock pass actually senior.', 349.74, 225);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Plan', 'Threat over sign leg decision I.', 300.61, 396);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Beautiful', 'Team maybe rise news.', 534.75, 754);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Safe', 'Four operation subject forget song leg.', 593.8, 337);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Guy', 'White guess spend.', 139.91, 981);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'Respond', 'Should set air pass cell.', 91.08, 443);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Camera', 'Sense international series.', 373.32, 657);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Return', 'Garden marriage decide hope into.', 652.28, 719);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'How', 'Thus simple beat.', 357.91, 3);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Cup', 'Happy difference cut.', 641.09, 575);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Pattern', 'Network raise travel red I.', 277.14, 699);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Many', 'Discussion police recently remain education happen.', 210.75, 18);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Over', 'Project total right relate.', 781.03, 732);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Television', 'Difficult card company.', 93.61, 863);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Than', 'Expert paper despite.', 853.13, 894);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Leg', 'Clearly teach also while somebody.', 512.26, 876);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Success', 'Charge change something.', 537.37, 361);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Sister', 'Magazine look something.', 300.85, 253);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Official', 'House fish away.', 696.98, 933);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Control', 'Smile between suggest huge kind voice.', 303.03, 45);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'Billion', 'Time white appear seven none it.', 135.64, 188);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Economy', 'Order smile social go edge yard.', 193.88, 975);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Pull', 'Dog onto just case.', 601.48, 685);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'As', 'Better history while matter we.', 75.39, 525);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Easy', 'Agree thing rest.', 578.86, 283);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Politics', 'Assume case hand.', 781.62, 379);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Begin', 'He economic stock.', 380.99, 309);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Agent', 'My discover also value yard education.', 75.51, 340);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Seat', 'Everyone employee experience.', 280.14, 11);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Despite', 'Six owner art suggest country lawyer.', 593.26, 843);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Him', 'What record leave.', 418.27, 329);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Change', 'Quality building tell truth.', 340.56, 363);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Within', 'Language report join.', 302.04, 199);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Candidate', 'Population agree town item you market.', 191.98, 850);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Skin', 'On sport player pass live owner.', 454.7, 273);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Available', 'Off mission address rate service defense.', 360.36, 458);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Cup', 'Which similar PM.', 52.67, 530);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Land', 'Summer indicate attack cause movie let.', 494.04, 272);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Pattern', 'Increase both either camera amount.', 865.24, 289);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Activity', 'Image later possible.', 729.96, 607);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Author', 'Trip industry mention.', 182.24, 630);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Black', 'Key quite arm range always produce.', 810.97, 811);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Understand', 'Include would rest.', 377.46, 132);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'East', 'Nearly before example.', 89.53, 779);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Drop', 'Dinner large can.', 563.01, 949);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Trouble', 'Four save attack third.', 86.49, 247);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Beautiful', 'Do line force rich.', 858.98, 940);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Theory', 'Edge example customer.', 74.0, 550);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Want', 'Staff music act media.', 230.1, 531);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Partner', 'Before together me size tough include.', 386.74, 483);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Movie', 'Energy by end security perhaps step.', 497.67, 312);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Real', 'Expect live country relate light.', 176.65, 822);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Official', 'Group do reason.', 620.11, 566);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Leader', 'Condition add his behavior bar.', 829.19, 507);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Final', 'Able take region event whole.', 167.83, 542);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Both', 'Religious expect north.', 571.78, 522);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Respond', 'Water company lot.', 78.37, 881);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Republican', 'Take push piece white toward member.', 115.83, 16);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Write', 'Region benefit ask result work become.', 457.81, 87);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Myself', 'Stock southern performance.', 512.9, 66);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Happen', 'Month notice wish when crime water.', 636.27, 352);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Experience', 'Fall sell bank pattern whom particular.', 81.46, 781);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Difficult', 'Happen girl usually able.', 317.52, 488);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'Property', 'Movement lead hear watch around.', 937.61, 708);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Toward', 'Shoulder head mention mind week.', 128.19, 144);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'Nothing', 'Shoulder pressure key wear follow thousand.', 784.96, 318);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Herself', 'Speak PM song if cover finally.', 279.72, 188);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Actually', 'Shoulder white kid.', 897.72, 891);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Manager', 'State under police low.', 96.84, 647);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Bring', 'Outside window past.', 62.62, 532);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Same', 'Mr party news onto two current.', 214.13, 856);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Effect', 'Particular whom along cut.', 813.64, 836);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Others', 'Wrong yes others keep child.', 676.2, 479);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Follow', 'Situation approach camera avoid.', 744.24, 323);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Hope', 'Middle market occur four.', 346.48, 264);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Land', 'Up describe technology name.', 758.54, 44);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'South', 'Foot plan pay.', 530.42, 917);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Bit', 'Model feeling under discussion management concern.', 822.72, 562);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Blue', 'Event wonder sort position term something.', 838.17, 752);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Society', 'Care develop relate inside.', 728.72, 758);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Per', 'Score amount agency local information what.', 85.43, 601);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Tax', 'American too lead three role stage.', 289.04, 431);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Pretty', 'Possible science walk take administration.', 829.22, 814);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Risk', 'Ready each discuss meet themselves.', 748.19, 922);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (5, 'Total', 'Less effort candidate.', 307.49, 236);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (2, 'Rise', 'Thus building wonder.', 31.62, 781);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (9, 'Ability', 'Scene safe remain back.', 121.21, 791);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (4, 'Follow', 'Now art against east any.', 852.6, 666);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (6, 'Manager', 'She person including politics responsibility.', 364.29, 411);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'New', 'Example speak baby product teach begin.', 266.89, 937);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (1, 'Between', 'Final fine what future.', 779.98, 741);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Then', 'Know water hour nor.', 685.04, 314);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (10, 'Seek', 'Girl fund system particularly choice.', 111.07, 83);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (7, 'Quite', 'Order song subject material plant.', 646.93, 791);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (3, 'Office', 'Treat economy answer while.', 365.3, 625);
INSERT INTO Product (Category_Id, Name, Description, Price, Stock_Quantity) VALUES (8, 'Several', 'Manage especially above left foot change.', 318.6, 352);